name: Deploy Portainer Stack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login into Docker Hub
        run: docker login ghcr.io -u masluse -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest ./ChatWebServer/
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

  deploy:
    needs: build  # Wait for the "build" job to complete
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Portainer Stack
        run: |
          cd /docker/docker-compose/test-deployment/
          docker-compose pull
          docker-compose up --force-recreate --build -d
